export const brand = {
  name: 'VoyageVista',
  mark: '✈',
  tagline: 'Discover your next adventure',
}

export const navCategories = [
  { id: 'packages', label: 'Packages', icon: '🌍', badge: '' },
  { id: 'experiences', label: 'Experiences', icon: '🎭', badge: 'NEW' },
  { id: 'adventures', label: 'Adventures', icon: '🏔️', badge: 'NEW' },
]

export const trendingDestinations = [
  {
    id: 'santorini',
    title: 'Santorini, Greece',
    price: '₹89,500',
    pricePerNight: '₹17,900',
    duration: 'for 5 nights',
    rating: 4.97,
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['beach', 'romantic'],
    urgency: '3 spots left',
    includes: ['flight', 'hotel', 'meals']
  },
  {
    id: 'bali',
    title: 'Bali, Indonesia',
    price: '₹62,000',
    pricePerNight: '₹10,333',
    duration: 'for 6 nights',
    rating: 4.92,
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['beach', 'adventure'],
    includes: ['hotel', 'meals', 'sightseeing']
  },
  {
    id: 'dubai',
    title: 'Dubai, UAE',
    price: '₹78,200',
    pricePerNight: '₹19,550',
    duration: 'for 4 nights',
    rating: 4.88,
    badge: 'Premium',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['city', 'premium'],
    includes: ['flight', 'hotel', 'sightseeing']
  },
  {
    id: 'paris',
    title: 'Paris, France',
    price: '₹1,05,000',
    pricePerNight: '₹21,000',
    duration: 'for 5 nights',
    rating: 4.95,
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['city', 'romantic'],
    includes: ['flight', 'hotel']
  },
  {
    id: 'maldives',
    title: 'Maldives',
    price: '₹1,45,000',
    pricePerNight: '₹36,250',
    duration: 'for 4 nights',
    rating: 4.99,
    badge: 'Premium',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['beach', 'romantic', 'premium'],
    urgency: 'Only 1 villa left',
    includes: ['flight', 'hotel', 'meals']
  },
  {
    id: 'switzerland',
    title: 'Switzerland',
    price: '₹1,35,000',
    pricePerNight: '₹22,500',
    duration: 'for 6 nights',
    rating: 4.94,
    badge: '',
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['mountains', 'adventure'],
    includes: ['hotel', 'sightseeing']
  },
  {
    id: 'tokyo',
    title: 'Tokyo, Japan',
    price: '₹98,500',
    pricePerNight: '₹19,700',
    duration: 'for 5 nights',
    rating: 4.91,
    badge: 'Trending',
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['city', 'culture'],
    includes: ['flight', 'hotel', 'sightseeing']
  },
]

export const weekendGetaways = [
  {
    id: 'goa',
    title: 'North Goa',
    price: '₹12,500',
    pricePerNight: '₹6,250',
    duration: 'for 2 nights',
    rating: 4.85,
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['beach', 'party'],
  },
  {
    id: 'udaipur',
    title: 'Udaipur, Rajasthan',
    price: '₹15,800',
    pricePerNight: '₹7,900',
    duration: 'for 2 nights',
    rating: 4.90,
    badge: 'Superhost',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['culture', 'romantic'],
  },
  {
    id: 'munnar',
    title: 'Munnar, Kerala',
    price: '₹11,200',
    pricePerNight: '₹5,600',
    duration: 'for 2 nights',
    rating: 4.78,
    badge: '',
    image: 'https://images.unsplash.com/photo-1516815231560-d1bbd6c13a5c?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['mountains', 'nature'],
  },
  {
    id: 'manali',
    title: 'Manali, Himachal',
    price: '₹9,800',
    pricePerNight: '₹4,900',
    duration: 'for 2 nights',
    rating: 4.82,
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['mountains', 'adventure'],
  },
  {
    id: 'rishikesh',
    title: 'Rishikesh, Uttarakhand',
    price: '₹8,500',
    pricePerNight: '₹4,250',
    duration: 'for 2 nights',
    rating: 4.76,
    badge: 'Adventure',
    image: 'https://images.unsplash.com/photo-1482938289607-e9573fc25ebb?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['adventure', 'nature'],
  },
  {
    id: 'jaipur',
    title: 'Jaipur, Rajasthan',
    price: '₹10,500',
    pricePerNight: '₹5,250',
    duration: 'for 2 nights',
    rating: 4.80,
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['culture'],
  },
  {
    id: 'ooty',
    title: 'Ooty, Tamil Nadu',
    price: '₹7,900',
    pricePerNight: '₹3,950',
    duration: 'for 2 nights',
    rating: 4.72,
    badge: '',
    image: 'https://images.unsplash.com/photo-1585409677983-0f6c41ca9c3b?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['mountains', 'nature'],
  },
]

export const honeymoonSpecials = [
  {
    id: 'bora-bora',
    title: 'Bora Bora, French Polynesia',
    price: '₹2,85,000',
    pricePerNight: '₹47,500',
    duration: 'for 6 nights',
    rating: 5.0,
    badge: 'Premium',
    image: 'https://images.unsplash.com/photo-1589197331516-4d84b72ebde3?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['beach', 'romantic', 'premium'],
    urgency: 'Popular for honeymooners',
    includes: ['flight', 'hotel', 'meals']
  },
  {
    id: 'amalfi',
    title: 'Amalfi Coast, Italy',
    price: '₹1,65,000',
    pricePerNight: '₹33,000',
    duration: 'for 5 nights',
    rating: 4.96,
    badge: 'Bestseller',
    image: 'https://images.unsplash.com/photo-1534113414509-0eec2bfb493f?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['romantic', 'culture'],
    includes: ['flight', 'hotel']
  },
  {
    id: 'seychelles',
    title: 'Seychelles',
    price: '₹1,95,000',
    pricePerNight: '₹39,000',
    duration: 'for 5 nights',
    rating: 4.98,
    badge: 'Premium',
    image: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['beach', 'romantic', 'premium'],
    includes: ['flight', 'hotel', 'meals']
  },
  {
    id: 'prague',
    title: 'Prague, Czech Republic',
    price: '₹92,000',
    pricePerNight: '₹23,000',
    duration: 'for 4 nights',
    rating: 4.89,
    badge: 'Trending',
    image: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['city', 'romantic', 'culture'],
  },
  {
    id: 'kyoto',
    title: 'Kyoto, Japan',
    price: '₹1,12,000',
    pricePerNight: '₹22,400',
    duration: 'for 5 nights',
    rating: 4.93,
    badge: '',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['culture', 'romantic'],
  },
  {
    id: 'capetown',
    title: 'Cape Town, South Africa',
    price: '₹1,08,000',
    pricePerNight: '₹21,600',
    duration: 'for 5 nights',
    rating: 4.87,
    badge: 'Trending',
    image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=800&q=80',
    liked: false,
    tags: ['adventure', 'nature', 'city'],
  },
]

export const navLinks = [
  { href: '#trending', label: 'Destinations' },
  { href: '#getaways', label: 'Getaways' },
  { href: '#honeymoon', label: 'Honeymoon' },
]

export const filterChips = [
  { id: 'all', label: 'All destinations' },
  { id: 'beach', label: 'Beachfront' },
  { id: 'romantic', label: 'Romantic' },
  { id: 'adventure', label: 'Adventure' },
  { id: 'city', label: 'City Tours' },
  { id: 'premium', label: 'Luxury' },
]

export const testimonials = [
  {
    id: 1,
    name: 'Sarah Jenkins',
    location: 'London, UK',
    trip: 'Bali Retreat',
    rating: 5,
    quote: 'Absolutely the best travel experience I have ever had. The attention to detail and 24/7 support made our trip flawless.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80',
    verified: true,
  },
  {
    id: 2,
    name: 'David Chen',
    location: 'Sydney, AU',
    trip: 'Swiss Alps',
    rating: 5,
    quote: 'Booking was so easy, and the prices were completely transparent. No hidden fees. Highly recommend VoyageVista!',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80',
    verified: true,
  },
  {
    id: 3,
    name: 'Elena Rodriguez',
    location: 'Madrid, ES',
    trip: 'Maldives Honeymoon',
    rating: 5,
    quote: 'Our honeymoon was magical. VoyageVista secured us an ocean-view villa that exceeded our wildest dreams.',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=100&q=80',
    verified: true,
  },
  {
    id: 4,
    name: 'Michael Scott',
    location: 'New York, US',
    trip: 'Tokyo Tour',
    rating: 4,
    quote: 'Great itinerary and fantastic guides. I only wish I could have stayed longer! Will definitely use them again.',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80',
    verified: true,
  },
]

export const whyChooseUs = [
  {
    id: 1,
    icon: '🛡️',
    title: 'Best Price Guarantee',
    description: 'We match any lower price you find online. No questions asked.',
  },
  {
    id: 2,
    icon: '💬',
    title: '24/7 Premium Support',
    description: 'Real travel experts available around the clock to assist you anywhere.',
  },
  {
    id: 3,
    icon: '📅',
    title: 'Flexible Cancellations',
    description: 'Change of plans? Easily cancel or modify your booking with zero hassle.',
  },
]
